<?php namespace HcDisat\Payment\Responses;

use HcDisat\Payment\Core\Contracts\RequestContract;

class Response extends AbstractResponse
{
    /**
     * Response constructor.
     * @param RequestContract $request
     * @param mixed $data
     */
    public function __construct(RequestContract $request, $data)
    {
        $this->request = $request;
        parse_str($data, $this->data);
    }

    /**
     * @inheritdoc
     */
    public function isPending()
    {
        return isset($this->data['PAYMENTINFO_0_PAYMENTSTATUS'])
        && $this->data['PAYMENTINFO_0_PAYMENTSTATUS'] == 'Pending';
    }

    /**
     * Is the response successful?
     *
     * @return boolean
     */
    public function isSuccessful()
    {
        return isset($this->data['ACK']) &&
            in_array(
                $this->data['ACK'],
                ['Success', 'SuccessWithWarning']
            );
    }

    /**
     * @inheritdoc
     */
    public function getTransactionReference()
    {
        $data = [
            'REFUNDTRANSACTIONID',
            'TRANSACTIONID',
            'PAYMENTINFO_0_TRANSACTIONID',
            'AUTHORIZATIONID'
        ];

        foreach ($data as $key) {
            if (isset($this->data[$key])) {
                return $this->data[$key];
            }
        }
    }

    /**
     * Get the transaction ID as generated by the merchant website.
     *
     * @return string
     */
    public function getTransactionId()
    {
        return $this->data['TRANSACTIONID'];
    }

    /**
     * @inheritdoc
     */
    public function getMessage()
    {
        return isset($this->data['L_LONGMESSAGE0']) ? $this->data['L_LONGMESSAGE0'] : null;
    }
}